#!/bin/bash
##
# Start magento
# Run this when ever you are ready to use the box
##
echo "Removing existing shop application"
docker rm -f shop >/dev/null

echo "Starting shop application"

echo "Executing : docker run -d -p 1009:80 -v \$(pwd)/www:/var/www --name shop magento web"
docker run -d -p 1009:80 -v $(pwd)/www:/var/www --name shop magento web >/dev/null

echo "Load http://192.168.99.100:1009"